<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\..\vehicle.proto" GrpcServices="Server" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\Vehicle.Application\Vehicle.Application.csproj" />
    <ProjectReference Include="..\Vehicle.Domain\Vehicle.Domain.csproj" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
